name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
        env: 
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - run: npm ci
      - run: npx sentry-cli login --auth-token=$SENTRY_AUTH_TOKEN && npm run build --if-present
      - run: npm test

      - name: Move source maps
        run: |
          mv ./dist/*/js/*.map ./source-maps/
          cp ./dist/*/js/*.js ./source-maps/

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            dist/
            source-maps/
